cc_library(
    name = "cache_controller",
    srcs = [
        "cache_controller.cpp",
        "obj_dir/Vcache_controller__ALL.a",
    ],
    hdrs = [
        "obj_dir/Vcache_contoller.h",
    ],
    includes = [
        "obj_dir/",
    ],
    deps = [
        "@verilator//:verilated",
        "@verilator//:verilated_vcd_c",
    ],
)
